### PR TITLE
Kb/ruby pg sqli

### PR DESCRIPTION
**Pull request by kurt-r2c**
Draft waiting on some Ruby fixes for `concat` and `<<`

Updates the following rules:

* `ruby-pg-sqli` to taint
* Fixes to `ruby-pg-sqli` tests to match new taint behavior
* ruby `bad-deserialization` to taint
* Fixes to `bad-deserialization` tests to match new taint behavior

### CODE REVIEW

**Comment by kurt-r2c** [comment]
known failing tests due to `concat(...)` and `<<` not propagating taint correctly

**Comment by kurt-r2c** [comment]
Ruby tests now passing, unrelated test failing. Investigating

**Comment by kurt-r2c** [comment]
Mystery solved. @IagoAbal's fix for `concat(...)` fixed two todo cases in tests that had typos in their annotations.

**Review by minusworld — APPROVED** [review]

**Comment by minusworld** [comment]
`test-historical` failures are expected given some updates to the latest Semgrep version

**Pull request merged**
