### PR TITLE
Filter $SOMETHING.dump(...) from tempfile-flush rule

### PR DESCRIPTION
**Pull request by minusworld**

### CODE REVIEW

**Comment by minusworld** [comment]
Based on FP here: https://github.com/returntocorp/semgrep/pull/2836#discussion_r601914772

**Comment by minusworld** [comment]
Fixes https://github.com/returntocorp/semgrep-rules/issues/1195

**Review by aryx — APPROVED** [review]
Cool! That was fast :)

**Comment by minusworld** [comment]
I put in the PR last night ;)

**Pull request merged**
