### PR TITLE
Terraform Rules based on Terragoat Scenarios

### PR DESCRIPTION
**Pull request by hunt3rkillerz**
Adding some additional terraform scanning rules based on the misconfigurations highlighted in [Terragoat](https://github.com/bridgecrewio/terragoat). 

**The following checks have been added:**

- Elastic Search domain encryption at rest check
- EKS public endpoint check
- ECR image scan on push check
- EBS volume encryption check

### CODE REVIEW

**Comment by ievans** [comment]
@hunt3rkillerz these rules look really cool and I'm excited to merge in the PR.

This repo previously didn't even have a license, so it was technically proprietary...we've fixed that and now have a proper license. But for new contributions we are asking people to sign a CLA. 

From the @cla-bot text: 

> Even though most of our projects are open-source, we ask contributors to sign a contributor license agreement before we merge your PR. There are a few reasons for this that we've learned over time: it's important to have an explicit statement that you wrote the code yourself, that no one else has a copyright claim on it, and it gives us as the long-term maintainers flexibility should we need to change the license in the future (though we don't plan to).

> We don't need your address or any other personal information, just a signature and your email address. Sorry to bug you with the legal stuff but the good news is once filed we can accept PRs from you on any project automatically!

> Please email cla@r2c.dev with a signed [copy of the contributor license agreement](https://r2c.dev/ContributorLicenseAgreement.pdf).

If signing the CLA is a blocker for you, please let me know and we can figure out some other way to accept your contribution!

**Comment by hunt3rkillerz** [comment]
> @hunt3rkillerz these rules look really cool and I'm excited to merge in the PR.
> 
> This repo previously didn't even have a license, so it was technically proprietary...we've fixed that and now have a proper license. But for new contributions we are asking people to sign a CLA.
> 
> From the @cla-bot text:
> 
> > Even though most of our projects are open-source, we ask contributors to sign a contributor license agreement before we merge your PR. There are a few reasons for this that we've learned over time: it's important to have an explicit statement that you wrote the code yourself, that no one else has a copyright claim on it, and it gives us as the long-term maintainers flexibility should we need to change the license in the future (though we don't plan to).
> 
> > We don't need your address or any other personal information, just a signature and your email address. Sorry to bug you with the legal stuff but the good news is once filed we can accept PRs from you on any project automatically!
> 
> > Please email [cla@r2c.dev](mailto:cla@r2c.dev) with a signed [copy of the contributor license agreement](https://r2c.dev/ContributorLicenseAgreement.pdf).
> 
> If signing the CLA is a blocker for you, please let me know and we can figure out some other way to accept your contribution!

Hi @ievans, I have no issues with the content of the agreement and would happily accept. However, I would prefer (if possible) to keep my name/email private.

**Comment by ievans** [comment]
Hey @hunt3rkillerz -- makes total sense to me! Let me figure out how we can make that happen and get back to you on this PR.

**Comment by ievans** [comment]
@hunt3rkillerz I discussed and we'd be happy to accept the contribution without a name/email as long as you're ok "signing" the CLA pdf with your Github username. 

I hate to ask you to fire up GPG (this would be easier if you have a [keybase](https://keybase.io) account and link it to your github), but...my thought is that the best practice is probably to then cryptographically sign the PDF with the public key associated with your github account (GPG key ID: 4AEE18F83AFDEB23, from looking at some of your commits--though `wget https://github.com/hunt3rkillerz.gpg` shows that the public key isn't listed yet, so maybe you'd need to do that?)

is doing the cryptographic signing doable for you? else I can see if we can relax that requirement :)

**Comment by hunt3rkillerz** [comment]
@ievans, I have cryptographically signed and sent over the CLA for this one. Was there anything else required?

**Comment by ievans** [comment]
@hunt3rkillerz sorry for the delay! Received and it made me remember how annoying GPG is -- thanks for doing that though, it was fun. Added you to the CLA-signed list so from now on you shouldn't have any more issues. However, you will still need to have a fictisious email address on yoru git commits that matches a public email listed in your github profile in order for @cla-bot to automatically mark you as approved. I'll override on this PR so you don't have to rewrite any commits :)

@cla-bot check

**Review by ievans — APPROVED** [review]

**Review by minusworld — APPROVED** [review]

**Pull request merged**
