### PR TITLE
Rule for wildcard CORS in FastAPI

### PR DESCRIPTION
**Pull request by theinfosecguy**
FastAPI supports adding middleware using `app.add_middleware()`. Developers usually add a wildcard origin policy, that can lead to security risks.

### CODE REVIEW

**Comment by inkz** [comment]
@theinfosecguy 
* Please add 
```
subcategory:
- vuln
```
like in https://github.com/returntocorp/semgrep-rules/blob/develop/python/flask/security/injection/nan-injection.yaml#L38

* and make sure that all `ruleid`s are in the right place
* also please add an `ok` test case with a non-vulnerable example

**Comment by theinfosecguy** [comment]
Thanks for the feedback, @inkz. I've updated the rule.

**Review by inkz — APPROVED** [review]

**Review by inkz — CHANGES_REQUESTED** [review]
Change code of the test to the following (I cant edit your branch):


```
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

origins = ["*"]


app.add_middleware(
    CORSMiddleware,
    # rule-id: wildcard-cors
    allow_origins=origins,
    allow_credentials=True,
    allow=["*"]
)


app.add_middleware(
    CORSMiddleware,
    # rule-id: wildcard-cors
    allow_origins=["*"],
    allow_credentials=True,
    allow=["*"]
)


app.add_middleware(
    CORSMiddleware,
    # ok-id: wildcard-cors
    allow_origins=["https://github.com"],
    allow_credentials=True,
    allow=["*"]
)

app.add_middleware(
    CORSMiddleware,
    # ok: wildcard-cors
    allow_origins=["https://github.com"],
    allow_credentials=True,
    allow=["www.semgrep.dev"]
)


@app.get("/")
async def main():
    return {"message": "Hello Semgrep"}
```

**Comment by theinfosecguy** [comment]
@inkz It's done.

**Comment by inkz** [comment]
> @inkz It's done.

@theinfosecguy 
Ok my bad, was too quick to copy paste :laughing: 
can you update it to:

```
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

origins = ["*"]


app.add_middleware(
    CORSMiddleware,
    # ruleid: wildcard-cors
    allow_origins=origins,
    allow_credentials=True,
    allow=["*"]
)


app.add_middleware(
    CORSMiddleware,
    # ruleid: wildcard-cors
    allow_origins=["*"],
    allow_credentials=True,
    allow=["*"]
)


app.add_middleware(
    CORSMiddleware,
    # ok: wildcard-cors
    allow_origins=["https://github.com"],
    allow_credentials=True,
    allow=["*"]
)

app.add_middleware(
    CORSMiddleware,
    # ok: wildcard-cors
    allow_origins=["https://github.com"],
    allow_credentials=True,
    allow=["www.semgrep.dev"]
)


@app.get("/")
async def main():
    return {"message": "Hello Semgrep"}
```

should work this time :smile: 

there must be `ruleid` comments, not `rule-id`s

**Comment by theinfosecguy** [comment]
hahah, my bad. 😆

Should work now.

**Review by inkz — APPROVED** [review]

**Comment by inkz** [comment]
ok now lgtm! thank you!

**Pull request merged**
