### PR TITLE
Update `vm-injection` rule

### PR DESCRIPTION
**Pull request by inkz**
merge `vm-injection-*` rules into one + add taint

### CODE REVIEW

**Comment by LewisArdern** [comment]
@inkz shouldn't we just update the audit rule which already exists vs 'deprecating' and making a new rule.

**Review by LewisArdern — CHANGES_REQUESTED** [review]
merge this into the audit rule IMO

**Comment by inkz** [comment]
@LewisArdern yes we should:) but it brakes the tests
tests do not allow for having multiple rules in one file and not having test cases for all of them
either deprecate all of them or none of them :(
I decided to create another rule and deprecate existing one

**Comment by LewisArdern** [comment]
I see, got it

**Review by LewisArdern — APPROVED** [review]

**Comment by inkz** [comment]
> merge this into the audit rule IMO

@LewisArdern I did it! :smile:  I was wrong, it was possible to merge :+1:

**Review by minusworld — APPROVED** [review]

**Pull request merged**
