### PR TITLE
Updating Node.js rules

### PR DESCRIPTION
**Pull request by inkz**
* simplifying old rules
* switching to taint mode

### CODE REVIEW

**Comment by minusworld** [comment]
@inkz  Could you benchmark the new taint rules vs. the old ones? You can use the code in this folder here: https://github.com/returntocorp/semgrep/tree/develop/perf

**Comment by minusworld** [comment]
I'm curious to see if the taint rules are faster or slower than their original counterparts! :D

**Comment by inkz** [comment]
@minusworld 
Taint rules perf test:
```json
[{
    "name": "semgrep.bench.axios.std",
    "time": 6.463316917419434
}, {
    "name": "semgrep.bench.axios.no-cache",
    "time": 6.892255067825317
}, {
    "name": "semgrep.bench.axios.max-cache",
    "time": 6.81252908706665
}, {
    "name": "semgrep.bench.axios.no-bloom",
    "time": 6.306408882141113
}, {
    "name": "semgrep.bench.axios.no-gc-tuning",
    "time": 5.470334053039551
}, {
    "name": "semgrep.bench.axios.set_filters",
    "time": 5.88432502746582
}, {
    "name": "semgrep.bench.axios.experimental",
    "time": 6.8796586990356445
}, {
    "name": "semgrep.bench.axios.experimental_and_fast",
    "time": 6.8110034465789795
}, {
    "name": "semgrep.bench.express.std",
    "time": 9.337934255599976
}, {
    "name": "semgrep.bench.express.no-cache",
    "time": 7.285827398300171
}, {
    "name": "semgrep.bench.express.max-cache",
    "time": 7.310151815414429
}, {
    "name": "semgrep.bench.express.no-bloom",
    "time": 7.448305368423462
}, {
    "name": "semgrep.bench.express.no-gc-tuning",
    "time": 9.717636823654175
}, {
    "name": "semgrep.bench.express.set_filters",
    "time": 8.621538639068604
}, {
    "name": "semgrep.bench.express.experimental",
    "time": 9.761693000793457
}, {
    "name": "semgrep.bench.express.experimental_and_fast",
    "time": 9.222865104675293
}]
```

regular rules perf:

```json
[{
    "name": "semgrep.bench.axios.std",
    "time": 1.7885584831237793
}, {
    "name": "semgrep.bench.axios.no-cache",
    "time": 1.7628602981567383
}, {
    "name": "semgrep.bench.axios.max-cache",
    "time": 1.8546171188354492
}, {
    "name": "semgrep.bench.axios.no-bloom",
    "time": 2.457138776779175
}, {
    "name": "semgrep.bench.axios.no-gc-tuning",
    "time": 2.1091248989105225
}, {
    "name": "semgrep.bench.axios.set_filters",
    "time": 1.8079161643981934
}, {
    "name": "semgrep.bench.axios.experimental",
    "time": 2.2240712642669678
}, {
    "name": "semgrep.bench.axios.experimental_and_fast",
    "time": 1.9918513298034668
}, {
    "name": "semgrep.bench.express.std",
    "time": 2.12347674369812
}, {
    "name": "semgrep.bench.express.no-cache",
    "time": 2.2926952838897705
}, {
    "name": "semgrep.bench.express.max-cache",
    "time": 2.481637954711914
}, {
    "name": "semgrep.bench.express.no-bloom",
    "time": 3.9481210708618164
}, {
    "name": "semgrep.bench.express.no-gc-tuning",
    "time": 3.533017873764038
}, {
    "name": "semgrep.bench.express.set_filters",
    "time": 3.158259153366089
}, {
    "name": "semgrep.bench.express.experimental",
    "time": 2.548386573791504
}, {
    "name": "semgrep.bench.express.experimental_and_fast",
    "time": 2.983673572540283
}]
```

so taint mode is slower :disappointed:

**Comment by minusworld** [comment]
@inkz Which version of Semgrep are you running?

cc @IagoAbal fysa

**Comment by inkz** [comment]
@minusworld `0.60.0`, did not notice that `0.61.0` is available, will try it also

**Comment by inkz** [comment]
on `0.61.0` numbers are pretty much the same

**Comment by IagoAbal** [comment]
I'll take a look.

**Comment by IagoAbal** [comment]
Well, we are not comparing apples to apples here. The main difference I see is that in the fake-taint rules you don't say that `$REQ` alone is a source of taint, whereas in the taint-rules you do. So the taint-rules suffer from the inefficient `pattern: $X` problem, but that has nothing to do with the taint engine.

**Comment by IagoAbal** [comment]
@inkz could you help me reproducing your perf comparison? Could you eg. push a branch to the Semgrep repo with whatever setup you did?

**Comment by minusworld** [comment]
@inkz Looks like there's some conflicts here, could we resolve them and try again? 😅

**Comment by inkz** [comment]
@IagoAbal yep, I'll share my testing config and files :+1: 

@minusworld sure, I also want to remove one pattern that Iago mentioned in his comment (nice catch by the way) https://github.com/returntocorp/semgrep-rules/pull/1392#issuecomment-895116431 and see how performance goes after that

**Comment by inkz** [comment]
@IagoAbal you are genius! a removed `- pattern: $REQ` from the rules and perf is back to the same as for "fake taint" rules now

do you still need my config? because I think performance issue does not exist anymore

cc @minusworld 
Taint rules perf test (after removing `- pattern: $REQ`):
```json
[{
    "name": "semgrep.bench.axios.std",
    "time": 1.7677702903747559
}, {
    "name": "semgrep.bench.axios.no-cache",
    "time": 1.7100844383239746
}, {
    "name": "semgrep.bench.axios.max-cache",
    "time": 1.713395595550537
}, {
    "name": "semgrep.bench.axios.no-bloom",
    "time": 1.761857271194458
}, {
    "name": "semgrep.bench.axios.no-gc-tuning",
    "time": 2.0871665477752686
}, {
    "name": "semgrep.bench.axios.set_filters",
    "time": 1.6663098335266113
}, {
    "name": "semgrep.bench.axios.experimental",
    "time": 1.7163362503051758
}, {
    "name": "semgrep.bench.axios.experimental_and_fast",
    "time": 1.721428394317627
}, {
    "name": "semgrep.bench.express.std",
    "time": 2.062638521194458
}, {
    "name": "semgrep.bench.express.no-cache",
    "time": 2.042210102081299
}, {
    "name": "semgrep.bench.express.max-cache",
    "time": 2.0708863735198975
}, {
    "name": "semgrep.bench.express.no-bloom",
    "time": 2.158113479614258
}, {
    "name": "semgrep.bench.express.no-gc-tuning",
    "time": 2.6868948936462402
}, {
    "name": "semgrep.bench.express.set_filters",
    "time": 2.0772597789764404
}, {
    "name": "semgrep.bench.express.experimental",
    "time": 2.124251127243042
}, {
    "name": "semgrep.bench.express.experimental_and_fast",
    "time": 2.1148765087127686
}]
```

**Comment by minusworld** [comment]
image

**Review by minusworld — APPROVED** [review]

**Pull request merged**
