### PR TITLE
add a new rule

### PR DESCRIPTION
**Pull request by gogo2464**
fixes #[1091](https://github.com/returntocorp/semgrep-rules/issues/1091).

It might have been already implemented in the [file](https://github.com/returntocorp/semgrep-rules/blob/develop/c/lang/security/insecure-use-printf-fn.yaml). In case of doubt fell free to watch my code.

Ready to merge.

### CODE REVIEW

**Review by inkz — CHANGES_REQUESTED** [review]
Thanks a lot for your help!
Could you please move the new rule and test for it to a separate files instead of adding it to `insecure-use-printf-fn.yaml`

**Comment by minusworld** [comment]
@gogo2464 I took the liberty of addressing @inkz 's comment and split things into separate files. To finish this PR, all you'll need to do now is sign the CLA as indicated in the comment above.

Thank you for your contribution! :)

**Comment by gogo2464** [comment]
@minusworld I will try to do it today. Thank you very much.

**Comment by gogo2464** [comment]
I try to sign the email with the key generated and pushed to github. It will take more time than expected.

**Comment by DrewDennison** [comment]
@gogo2464 we have a new CLA bot that you can sign with your github login without messing with the PGP signing. Of course happy to take that as well but this might be an easier flow

**Comment by gogo2464** [comment]
@DrewDennison excellent. I was trying to sign for weeks! I am going to try to push again to see. Do not forget me.

**Comment by gogo2464** [comment]
@minusworld I have forced-push. I should not have done that. I have overwritten your change. I really hope you have a copy on your computer!

Do you want that I solve this comment alone https://github.com/returntocorp/semgrep-rules/pull/1092#pullrequestreview-590176851 if you do not have a copy.

:(

**Comment by minusworld** [comment]
I have it! 🎉  There seems to be an issue with the pre-commit job right now; once that's resolved we'll get this merged.

**Comment by minusworld** [comment]
Woohoo! 🙌  Got it. @inkz just need your approval.

**Comment by gogo2464** [comment]
@minusworld yes it sounds perfect. Ready to merge.

**Comment by minusworld** [comment]
@inkz nudge

**Review by inkz — APPROVED** [review]
lgtm!

**Pull request merged**
