### PR TITLE
Flask without decorators support for ssrf-requests

### PR DESCRIPTION
**Pull request by nightshiba**

### CODE REVIEW

**Comment by nightshiba** [comment]
Hi, can someone please review it and merge it?
The current version is not working for the pretty common case of direct method usage.

**Comment by p4p3r** [comment]
@nightshiba could you please update your branch by merging the current develop into it? This should fix the failing `rules-test-develop` test and allow me to merge.
Thanks in advance!

**Comment by nightshiba** [comment]
> @nightshiba could you please update your branch by merging the current develop into it? This should fix the failing `rules-test-develop` test and allow me to merge. Thanks in advance!

Hello @p4p3r, I've updated my branch as requested :+1:

**Review by p4p3r — APPROVED** [review]
Thanks for you contribution @nightshiba !
LGTM, I'm going to merge into develop and it will trickle down into release likely later today!

**Pull request merged**
