### PR TITLE
Rename js-open-redirect rule files

### PR DESCRIPTION
**Pull request by inkz**
fix filenames

### CODE REVIEW

**Comment by colleend** [comment]
are there currently any packs that include these files?

**Comment by inkz** [comment]
@colleend 
yep, it is for `clientside-js` pack: https://github.com/returntocorp/semgrep-rule-packs/blob/master/clientside-js.json

**Comment by colleend** [comment]
gotcha!

**Review by colleend — APPROVED** [review]

**Comment by ievans** [comment]
@colleend @inkz can this be closed or merged?

**Comment by inkz** [comment]
@ievans my bad, closing now, will review and reopen on new code if needed

**Pull request closed without merging**
