### PR TITLE
add rules for slow semgrep patterns

### PR DESCRIPTION
**Pull request by inkz**

### CODE REVIEW

**Comment by colleend** [comment]
ohh exciting!! thanks for doing this -- have you tried running these rules on our current `semgrep-rules` repository? (I feel like I am guilty of doing some of things 😱 )

**Comment by inkz** [comment]
@colleend Oh yeah me too, this pull is actually based on my mistakes mostly :laughing:

**Review by colleend — APPROVED** [review]
looks good to me though 👍

**Comment by minusworld** [comment]
⚠️ Hold off on merging these until we resolve something external

**Comment by minusworld** [comment]
@inkz This can be merged now, but may require moving the rules from `meta/` to `yaml/semgrep/`

**Comment by minusworld** [comment]
Closes https://github.com/returntocorp/enterprise/issues/631

**Pull request merged**
