### PR TITLE
fix: Exclude access to request.user from view

### PR DESCRIPTION
**Pull request by tartieret**
The django test for access to foreign keys exclude `request.user` but fails if we do this within a view and use `self.request.user`. This PR fixes the issue by excluding this common use case in django & django rest framework.

### CODE REVIEW

**Comment by tartieret** [comment]
@0xDC0DE sorry to ping you, but I saw that you recently approved another django-related rule and that you work at Semgrep. I am wondering if we could get this merged as it leads to false positive and would be a super quick review?

**Review by p4p3r — APPROVED** [review]
@tartieret, it looks good to me!

**Comment by p4p3r** [comment]
I'm going to merge in `develop` and it will make its way into `release` later this week!

**Comment by tartieret** [comment]
> I'm going to merge in `develop` and it will make its way into `release` later this week!

Thanks a lot!

**Pull request merged**
