### PR TITLE
Update ELB security policies

### PR DESCRIPTION
**Pull request by allanbreyes**
The current rule produces findings for ELB security policies that are TLS 1.2 and TLS 1.3, including the AWS-recommended one (`ELBSecurityPolicy-TLS13-1-2-2021-06`), which is TLS 1.3 with TLS 1.2 compatibility.

This pull request updates the patterns to regexes that should be a little more future proof.

Reference: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies

### CODE REVIEW

**Review by kurt-r2c — APPROVED** [review]
we like less brittleness

**Comment by allanbreyes** [comment]
Looks like a perf test failed: https://github.com/returntocorp/semgrep-rules/actions/runs/6668912440/job/18230637467

Seems to be from a flake or networking issue?

```
curl: (6) Could not resolve host: argoworkflows-dev.corp.r2c.dev
```

Please advise on how to proceed. Thank you!

**Comment by kurt-r2c** [comment]
@allanbreyes you were missing changes from upstream related to the decommissioning of some old infrastructure. Test should pass now.

**Comment by allanbreyes** [comment]
Thanks for the review and merge!

**Pull request merged**
