### PR TITLE
separate open redirect from tainted-url-host

### PR DESCRIPTION
**Pull request by hex0punk**
rule  go.lang.security.injection.tainted-url-host.tainted-url-host its well crafted, but it catches a lot of open redirects and marks them as SSRF, often TP findings, but simple redirects none the less. I am proposing instead adding a separate rule for open redirects, which typically would have a lesser impact that an SSRF.  While I am sure there are some edge cases that Open Redirects can lead to SSRF in Golang, I have not seen a good example either in the web or my work in security (consulting or otherwise).

### CODE REVIEW

**Comment by LewisArdern** [comment]
@hex0punk can you remove it from the previous rule also?

**Comment by hex0punk** [comment]
> @hex0punk can you remove it from the previous rule also?

Done. Note `go fmt` updated the tabs so it looks like there are more changes than there were

**Comment by LewisArdern** [comment]
One nitpick can you also change the metadata to match the previous rule, you changed them both to low
```
      impact: MEDIUM
      likelihood: MEDIUM
``` 

etc that make sense for the non vuln description

**Comment by hex0punk** [comment]
> One nitpick can you also change the metadata to match the previous rule, you changed them both to low
> 
> ```
>       impact: MEDIUM
>       likelihood: MEDIUM
> ```
> 
> etc that make sense for the non vuln description

Yep, done.

**Comment by LewisArdern** [comment]
@hex0punk can u merge in the latest develop and we can get this merged

**Review by LewisArdern — APPROVED** [review]

**Pull request merged**
