### PR TITLE
python: Future-proof use-ftp-tls for stdlib libdefs

### PR DESCRIPTION
**Pull request by nmote**
Explanation in the rule

### CODE REVIEW

**Review by yosefAlsuhaibani — APPROVED** [review]
Yeah this looks good: appreciate the in depth comment!

**Comment by nmote** [comment]
Thanks! I'll wait a bit to merge in case someone from the Code team wants to weigh in.

**Comment by inkz** [comment]
@nmote `ftplib.FTP(...)` pattern should always match only `ftplib.FTP`, adding exclusion for FTP_TLS would make sense if we had something like this:
```
  patterns:
    - pattern: ftplib.$WHATEVER(...)
    - pattern-not: ftplib.FTP_TLS(...)
```

I recommend adding test case with FTP_TLS first, then see how the rule performs and if updates needed add them

**Comment by kopecs** [comment]
@inkz I think Nat is saying that in ftplib `FTP_TLS` subclasses `FTP`, and we have the pattern `A` match `B` when `A` is a subclass of `B`. Previously we didn't know that `FTP_TLS` inherited from `FTP`, but we now do/will know with interfile.

**Comment by nmote** [comment]
@inkz In fact there is such a test case, and it failed on the branch I'm using to develop Python libdefs, for the reason that @kopecs explained. That's why I put up this PR.

**Comment by nmote** [comment]
This is the test case that fails when this rule is run using libdefs: https://github.com/semgrep/semgrep-rules/blob/a326e6f005b08bc7823d5483a3392a1cafca913e/python/lang/security/audit/insecure-transport/ftplib/use-ftp-tls.py#L9-L10

**Review by kopecs — APPROVED** [review]

**Comment by inkz** [comment]
Interesting! thanks for clarification @nmote @kopecs 
is information about `ftplib` classes hardcoded in the engine?

**Comment by nmote** [comment]
It will be for the interfile engine, just like we currently hardcode information about the Java standard library.

**Comment by inkz** [comment]
@nmote Cool! thanks

**Pull request merged**
