### PR TITLE
Fix typos, spaces, mistakes in rules description

### PR DESCRIPTION
**Pull request by artem-fedorov**

### CODE REVIEW

**Comment by 0xDC0DE** [comment]
Hi @artem-fedorov, these contributions look great, thanks for you meticulous work!

We had some trouble with our CI checks, but these should be fixed. If you can merge our develop branch into yours, the CI checks should run successfully and we can continue reviewing your contribution.

**Comment by artem-fedorov** [comment]
Hey
how to rerun CI?

**Comment by artem-fedorov** [comment]
Hey @0xDC0DE 
Should I add anything more to this PR?

**Comment by colleend** [comment]
hi @artem-fedorov, thanks for your contribution! Would you mind doing one last merge to develop? That should fix all the CI failures and we can merge 😄

**Comment by artem-fedorov** [comment]
@colleend 
Sure, I did it

**Review by colleend — APPROVED** [review]
lgtm

**Pull request merged**
