### PR TITLE
Update rule - python.django.correctness.nontext-field-must-set-null-true

### PR DESCRIPTION
**Pull request by Zebradil**
Adds [`FileField`](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.FileField) and [`ImageField`](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.ImageField) to the list of text fields.

### CODE REVIEW

**Comment by Zebradil** [comment]
CLA is sent.

**Comment by chmccreery** [comment]
@cla-bot check

**Comment by chmccreery** [comment]
@cla-bot check

**Comment by chmccreery** [comment]
@cla-bot check

**Comment by minusworld** [comment]
@cla-bot check

**Review by minusworld — APPROVED** [review]
lgtm! Thank you!

**Pull request merged**
