### PR TITLE
Update workflow file to use make

### PR DESCRIPTION
**Pull request by minusworld**

### CODE REVIEW

**Comment by minusworld** [comment]
https://github.com/returntocorp/semgrep-rules/issues/2380

**Comment by mjambon** [comment]
Thanks @minusworld, it's failing as expected based on what @aryx reported earlier today.

**Comment by mjambon** [comment]
Actually I was wrong:
* it's my script that's broken. The fix is there: https://github.com/returntocorp/semgrep-rules/pull/2406
* I don't get test failures after that when I run `make test` locally... which is good.

**Review by mjambon — APPROVED** [review]

**Comment by mjambon** [comment]
Thank you, @minusworld !

**Pull request merged**
