### PR TITLE
Usage of weak RSA encryption padding in C#

### PR DESCRIPTION
**Pull request by mtausig**
Add a rule detecting outdated cryptography in C#.

### CODE REVIEW

**Comment by inkz** [comment]
@mtausig thank you!:pray: please add `technology` field to metadata (example: https://github.com/returntocorp/semgrep-rules/blob/develop/csharp/dotnet/security/mvc-missing-antiforgery.yaml#L41)

**Review by inkz — APPROVED** [review]
lgtm

**Comment by mtausig** [comment]
If I want to add more similar rules (usage of bad cryptographic algorithms), should I collect them in a single yaml files or have one file per rule?

**Comment by kurt-r2c** [comment]
@mtausig one file per rule is the current best-practice guideline.

**Comment by mtausig** [comment]
Allright, then I will add them one file and PR per rule.

One last thing: Could you maybe add the `hacktoberfest-accepted` label to this PR?

**Comment by colleend** [comment]
Done! Thanks for the contribution!

**Pull request merged**
