### PR TITLE
add require-request rule

### PR DESCRIPTION
**Pull request by inkz**
rule for: https://github.com/returntocorp/semgrep-rules/issues/606

### CODE REVIEW

**Comment by minusworld** [comment]
I think that using `patter-either` with `pattern-inside` gets very weird... I am curious to see how these do running on platform. Could you try that out?

**Comment by inkz** [comment]
@minusworld yep sure! I'll also try to extend examples to test different behaviour

**Comment by inkz** [comment]
@minusworld 
platform: https://dev.massive.ret2.co/jobs/1086
updated test examples also

**Review by minusworld — APPROVED** [review]
Scan looks good, thanks!

**Pull request merged**
