### PR TITLE
Add AngularJS Security Rules

### PR DESCRIPTION
**Pull request by snoopysecurity**
This PR can be used to add the following security rules from `eslint-plugin-angularjs-security-rules` for users wanting to use semgrep instead of ESLint for AngularJS security linting. https://github.com/LewisArdern/eslint-plugin-angularjs-security-rules

* detect-angular-element-methods
* detect-angular-open-redirect
* detect-angular-resource-loading
* detect-angular-sce-disabled
* detect-third-party-angular-translate
* detect-angular-trustAs-method
* detect-angular-trustAsCss-method
* detect-angular-trustAsHtml-method
* detect-angular-trustAsJs-method
* detect-angular-trustAsResourceUrl-method 
* detect-angular-trustAsUrl-method

### CODE REVIEW

**Comment by snoopysecurity** [comment]
Mind taking a look at this @minusworld?

**Comment by minusworld** [comment]
It looks like the rules are missing the `languages` key, which is causing a schema error. (The error message is not very helpful, is it? It looks like it might even be incorrect.)

If you add in 

```yaml
languages:
- javascript
```

I think that will clear things up. 🤞

**Review by minusworld — APPROVED** [review]
\o/ 👍

**Comment by snoopysecurity** [comment]
Can I close this and open a new PR without the other pull requests, made a mistake will trying to fix the conflict with the base branch. Commit 2eb6e70c8fd8ac6a398897a82b1f1887879eed61 shouldn't theoretically be merged, i didn't rebase properly it seems

**Comment by snoopysecurity** [comment]
actually i ll close this

**Pull request closed without merging**
