### PR TITLE
chore: use deepok to mark lines as ok when run with the pro engine

### PR DESCRIPTION
**Pull request by emjin**
We have deepruleid to mark lines as matching only with the pro engine, but we didn't have anything to mark lines as ok only with the pro engine. deepok is intended for that.

This PR updates annotations to use deepok.

### CODE REVIEW

**Comment by emjin** [comment]
Failing tests are validation errors, appear unrelated (they're probably due to Brandon's changes)

**Comment by colleend** [comment]
yep, seems like the validation errors are unrelated and historical isn't passing bc of some type inference checks. Lgtm -- thanks emma!

**Review by colleend — APPROVED** [review]

**Comment by p4p3r** [comment]
I merged all the latest changes in develop (including Brandon's changes to regex metavars capture), but tests are still reported as failing. Is that expected?

**Comment by colleend** [comment]
nope, that's not expected -- I suspect that this is because `ruleid: deepok: ` isn't recognized by the `semgrep --test` test script. 

I can look into it for a bit 👍 

---
edit: yep: 
```
Could not parse         // ruleid: deepok: tainted-sql-string as a test annotation in file /Users/chai/Desktop/semgrep_repos/semgrep-rules/java/spring/security/injection/tainted-sql-string.java. Skipping this line
Could not parse         // ruleid: deepok: tainted-sql-string as a test annotation in file /Users/chai/Desktop/semgrep_repos/semgrep-rules/java/spring/security/injection/tainted-sql-string.java. Skipping this line
```

**Comment by emjin** [comment]
Oh no, --test must check it differently. I could change the format of this annotation if that would be the simplest way

**Comment by colleend** [comment]
passes develop now! I will merge :D

**Pull request merged**
