### PR TITLE
C# lang insecure deserialization

### PR DESCRIPTION
**Pull request by ahmetak4n**
C# insecure deserialization detection rules (Friday the 13th Json - https://www.blackhat.com/docs/us-17/thursday/us-17-Munoz-Friday-The-13th-JSON-Attacks-wp.pdf)

- Newtonsoft.Json
- FastJSON
- BinaryFormatter
- LosFormatter
- SoapFormatter
- NetDataContract
- FsPickler

### CODE REVIEW

**Comment by mschwager** [comment]
Wow, this is great! Thanks for the contributions.

Before merging, let's fix up a few things:

- It looks like CI is failing with a few minor nits, let's clean those up.
- By convention we put each rule into its own file (I know we have a few legacy rules breaking this convention :/). Can you split these into multiple files?
- I think we'll be less likely to have filesystem and shell weirdness if we use the `cs` top-level directory instead of `c#`.

Once those things are cleaned up we should be good to go, thanks again!

**Comment by mschwager** [comment]
Oh, and we have a convenient way for [testing rules](https://semgrep.dev/docs/writing-rules/testing-rules/) as well. That should help with the `test-develop` failures :+1:

**Comment by mschwager** [comment]
Hi there, sorry, one more thing. Would you mind converting the `_` -> `-` in your file names? This is another convention that I should've specified previously :disappointed:

**Review by mschwager — APPROVED** [review]
Nice! Thanks again

**Comment by daghan** [comment]
Hey @ahmetak4n, if you can DM me on our slack channel (https://r2c.dev/slack) I'll send you some swag.

**Pull request merged**
