### PR TITLE
enable case-insensitive php tests

### PR DESCRIPTION
**Pull request by akuhlens**
Updates Php tests to allow case insensitive identifiers. This corresponds to the addition of the feature in [PR #8356 in semgrep repo](https://github.com/returntocorp/semgrep/pull/8356).

I am not aware of the best way to smoothly transition both repos in tandem. So I would love any assistance you could provide on that front.

### CODE REVIEW

**Review by LewisArdern — APPROVED** [review]
to unblock semgrep build

**Comment by aryx** [comment]
@akuhlens the way it works is you make a PR to semgrep-rules, and don't care about the CI results (it will fail), then you make a PR in semgrep, with its semgrep-rules submodule updated to point to this PR, and there the CI results should all pass! then you merge in semgrep, wait a few hours, and rerun the CI in semgrep-rules and it should use the latest develop and pass. Feel free to update our Notion page for this process :)

**Comment by kurt-r2c** [comment]
@akuhlens is this still waiting on Semgrep changes?

**Comment by aryx** [comment]
yes, still waiting. This should not be merged.

**Comment by akuhlens** [comment]
Sorry that this is taking longer than it should. Due to some miscommunication on my part I went down a rabbit whole that was a little too big of scope for the original PR. I am trying to tidy things up and get the original PR and this diff merged as soon as possible.

**Comment by akuhlens** [comment]
@LewisArdern  Just a heads up. I had to change some testing annotations for secrets to get semgrep's develop branch to run complete all the tests on this side. The changes are included in commit [1ac4d20](https://github.com/returntocorp/semgrep-rules/pull/3013/commits/1ac4d20a63f5a2c6387f6cf98af3fd18cb70374c). As far as I can tell these are all just cases of the test working when it wasn't expected to. 
Screenshot 2023-08-13 at 3 31 08 PM

**Pull request merged**
