### PR TITLE
Update useless-comparison.yaml

### PR DESCRIPTION
**Pull request by moshekaplan**
Add additional detail to error message.

### CODE REVIEW

**Comment by minusworld** [comment]
@cla-bot check

**Comment by minusworld** [comment]
Hey @moshekaplan, thanks for this small update! Clean, clear messages are the best. 😉 
We recently integrated a contributor license agreement requirement, as indicated in the message above. If you follow the instructions, we can get this merged.
If you have already sent a CLA, let us know. Thanks!

**Comment by moshekaplan** [comment]
I've e-signed the cla. However, the old CLA check is still in use and so blocking the merge

**Review by DrewDennison — APPROVED** [review]

**Comment by DrewDennison** [comment]
@moshekaplan thanks for e-signing the CLA. It's ready to merge now

**Pull request merged**
