### PR TITLE
Add meta rules for metadata fields' format

### PR DESCRIPTION
**Pull request by underyx**

### CODE REVIEW

**Review by mschwager — APPROVED** [review]
Generally LGTM :+1: can you also add some basic tests for the new meta rules?

**Comment by underyx** [comment]
> Generally LGTM 👍 can you also add some basic tests for the new meta rules?

I wanted to but I saw the existing ones didn't have any and assumed that's because testing meta rules doesn't work somehow 🤔

**Comment by mschwager** [comment]
It should work with the new [`.test.yaml` functionality](https://semgrep.dev/docs/writing-rules/testing-rules/)

**Comment by underyx** [comment]
Done, thanks for the review!

**Pull request merged**
