### PR TITLE
Added basic Wordpress Plugin Rules

### PR DESCRIPTION
**Pull request by p3n7a90n**
Added basic Wordpress Plugin Rules based on the wpscan plugin cheatsheet wiki
https://github.com/wpscanteam/wpscan/wiki/WordPress-Plugin-Security-Testing-Cheat-Sheet

### CODE REVIEW

**Comment by enncoded** [comment]
Hi @p3n7a90n, thanks for adding these!

I have some concerns about these possibly being a little noisy, as they'd fire in non-WordPress PHP code. Since the flag function calls without taking the code's context into account, they seem like audit style rules. 

As such, could you:
* Prepend `wp-` and append `-audit` to the filenames and rule ids so it's more clear that these are for wordpress specifically and that they're also [audit-style rules](https://semgrep.dev/docs/contributing/contributing-to-semgrep-rules-repository/#audit)? eg: `ajax_no_auth_and_auth_hooks` becomes `wp-ajax_no_auth_and_auth_hooks-audit`.

* Augment the rule messages and the metadata with the required info according to the [rule contribution guidelines](https://semgrep.dev/docs/contributing/contributing-to-semgrep-rules-repository/#rule-messages)?

* Could you also specify WordPress-specific paths in the rules as well, so that we can [limit these rules to only fire in WordPress projects](https://semgrep.dev/docs/writing-rules/rule-syntax/#limiting-a-rule-to-paths)? I think the following should be good enough:
```
paths:
  include:
    - wp-*/**/*.php
    - wp-*.php
```

Let me know if you have any questions.

**Comment by p3n7a90n** [comment]
Hi @enncoded ,

Thanks for the review.
I have added the changes mentioned below.

- Modified the rule ids and files name as per your comment and moved the files to audit directory to make it more clear.
- Modified the rule messages and added the metadata as per guidelines.
- Added the below pattern in paths to make it restrictive to the wp plugins only.
```
paths:
      include:
        - wp-content/plugins/**/*.php
```

**Comment by enncoded** [comment]
Hey @p3n7a90n! 

These changes look great, and I appreciate you taking the time to do them! Unfortunately, we'll need to make a couple more to make all tests pass. Should be a bit less tedious this time.
To ensure that these changes will work and to save you some time, I tested all of them in a test branch here https://github.com/returntocorp/semgrep-rules/pull/2570. I won't merge it or anything, but it's there for your reference if you need it. I'll delete it once this is merged.

* Some of the tests no longer work because the Python test runner repository that they use changed some stuff upstream. This has been [fixed in our repo](https://github.com/returntocorp/semgrep-rules/pull/2571), so you'll need to pull and rebase your changes on develop.
* Because we restricted the paths that these rules run on, you'll need to move the `.php` test files into a directory that fits that schema. Let's put them in `tests/wp-content/plugins/`. I totally forgot about that the first time, my bad!
Here's the output from running `tree` in `semgrep-rules/php/wordpress-plugins/security/audit` for your reference:
```
~/semgrep-rules/php/wordpress-plugins/security/audit enno-test-asdfklj
❯ tree
.
├── tests
│   └── wp-content
│       └── plugins
│           ├── wp-ajax-no-auth-and-auth-hooks-audit.php
│           ├── wp-authorisation-checks-audit.php
│           ├── wp-code-execution-audit.php
│           ├── wp-command-execution-audit.php
│           ├── wp-csrf-audit.php
│           ├── wp-file-download-audit.php
│           ├── wp-file-inclusion-audit.php
│           ├── wp-file-manipulation-audit.php
│           ├── wp-open-redirect-audit.php
│           ├── wp-php-object-injection-audit.php
│           └── wp-sql-injection-audit.php
├── wp-ajax-no-auth-and-auth-hooks-audit.yaml
├── wp-authorisation-checks-audit.yaml
├── wp-code-execution-audit.yaml
├── wp-command-execution-audit.yaml
├── wp-csrf-audit.yaml
├── wp-file-download-audit.yaml
├── wp-file-inclusion-audit.yaml
├── wp-file-manipulation-audit.yaml
├── wp-open-redirect-audit.yaml
├── wp-php-object-injection-audit.yaml
└── wp-sql-injection-audit.yaml
```
* You'll need to change the format of the CWE fields to fit the [required format](https://semgrep.dev/docs/contributing/contributing-to-semgrep-rules-repository/#cwe). This test didn't run in your PR so far because we need to make the change in the first bullet point first. Here's the error that you would get if the test ran without changing those CWE fields https://github.com/returntocorp/semgrep-rules/actions/runs/3519384396/jobs/5899279001#step:7:11.
  * Specifically, the CWE 285 ones should just be `CWE-285: Improper Authorization` instead of `CWE 285: The software does not perform or incorrectly performs an authorization check when an actor attempts to access a resource or perform an action.`
  * The CWE 73 ones should be `CWE-73: External Control of File Name or Path` instead of `CWE 73: The software allows user input to control or influence paths or file names that are used in filesystem operations.`
  * All of them should have a dash between `CWE` and the corresponding number, instead of a space like you currently have. For example, all of yours are currently formatted like `CWE 502: Deserialization of Untrusted Data`, but they should be `CWE-502: Deserialization of Untrusted Data`.

Sorry to be making you do a bunch of housekeeping stuff! You caught us at a bad time where our tests were broken and our metadata guideline documentation is still semi-wip. This _should_ be the last set of changes.

**Comment by p3n7a90n** [comment]
Hi @enncoded ,

Thanks for the detailed explanation on what changes need to be done.
I have added the changes mentioned below.
-  Moved all the test files to tests/wp-content/plugins and merged the develop branch changes as well.
-  Modified the format of the CWE message to make it proper according to your comment/guidelines.

**Review by 0xDC0DE — APPROVED** [review]

**Comment by 0xDC0DE** [comment]
That looks good to me! Thanks for your contribution @p3n7a90n !

**Comment by alexgit2k** [comment]
Note: `current_user_can` should be removed from `regex: current_user_can|is_admin|is_user_logged_in|is_user_admin` in [wp-authorisation-checks-audit.yaml](https://github.com/returntocorp/semgrep-rules/blob/develop/php/wordpress-plugins/security/audit/wp-authorisation-checks-audit.yaml#L7) as accordingly to Wordpress `current_user_can` is the proper way: https://github.com/wpscanteam/wpscan/wiki/WordPress-Plugin-Security-Testing-Cheat-Sheet#authorisation
> `current_user_can()` used for checking authorisation. **This is what should be used to check authorisation.**

**Comment by p3n7a90n** [comment]
Yeah, Its a proper way for the authorisation checks but sometimes developer makes mistake while passing the capability argument.
These are just the audit rules that can help to give an idea on the authorisation checks in the  plugins.
@alexgit2k

**Pull request merged**
