### PR TITLE
Add Ruby check secrets

### PR DESCRIPTION
**Pull request by clintgibler**

### CODE REVIEW

**Review by minusworld — APPROVED** [review]

**Comment by minusworld** [comment]
Oh, looks like `pattern-where-python` needs to explicitly return a boolean

**Comment by clintgibler** [comment]
```
python where expression needs boolean output but got: <re.Match object; span=(0, 8), match='password'> for import re
re.match(r"password|secret|(rest_auth_site|api)_key$", vars['$X'].lower())
```

**Comment by mschwager** [comment]
I believe we can better achieve this will `metavariable-regex` now. Then there's no need for code execution.

**Comment by ievans** [comment]
@clintgibler want to fix or close?

**Comment by minusworld** [comment]
Closing due to inactivity. Reopen this PR if still relevant.

**Pull request closed without merging**
