### PR TITLE
fix false positive for missing-csrf-protection

### PR DESCRIPTION
**Pull request by obeleh**
The following code would trigger a false positive

```
class OkController < ActionController::Base

  protect_from_forgery prepend: true, with: :exception

  puts "do more stuff"

end 
```

### CODE REVIEW

**Comment by minusworld** [comment]
Looks like tests pass! Thanks!
I'll fix up the pre-commit issues, and if you'll sign the CLA above we'll get this merged in.
Thank you!

**Comment by obeleh** [comment]
I've just emailed my contributor agreement.

**Comment by minusworld** [comment]
@cla-bot check

**Comment by obeleh** [comment]
@cla-bot check

**Comment by minusworld** [comment]
Not sure what's happening, I'll investigate

**Comment by minusworld** [comment]
We received your CLA, so this seems like some error

**Comment by minusworld** [comment]
@cla-bot check

**Comment by minusworld** [comment]
@cla-bot check

**Comment by minusworld** [comment]
Ugh, so close

**Comment by minusworld** [comment]
There we go 👍

**Comment by minusworld** [comment]
Sorry for the trouble @obeleh ! Thanks for the contribution! 🤘

**Review by minusworld — APPROVED** [review]

**Review by brendongo — APPROVED** [review]

**Pull request merged**
