### PR TITLE
added file finally

### PR DESCRIPTION
**Pull request by colleend**

### CODE REVIEW

**Review by mschwager — APPROVED** [review]
It's back!

**Comment by colleend** [comment]
never thought i'd see it again 😩

**Comment by gastonstrizzolo** [comment]
Hi @colleend, thanks for adding this, do you know how to run this file? I don't fully understand if the Redos detector is integrated to Semgrep because if I run Dlint in my code it has some findings, but with Semgrep I don't know if I have to import something

**Comment by colleend** [comment]
Hi, thanks for the question -- currently the dlint redos detector isn't fully integrated into semgrep. Currently we're not focusing on redos, so it will be a while before we are able to make progress with this.

**Pull request merged**
