### PR TITLE
dockerfile/use-workdir: improved match and cleaner message

### PR DESCRIPTION
**Pull request by p4p3r**
Improved both message and match to address developer sentiment.
It requires Semgrep > 0.102.0 (unreleased at the moment).

### CODE REVIEW

**Review by colleend — APPROVED** [review]
lgtm :D

**Comment by p4p3r** [comment]
Note: historical semgrep test (v0.100.0) is expected to be failing like this because this PR requires >v0.102.0

**Comment by colleend** [comment]
ah I see -- v103 was released yesterday by nathan! I would be down to merge this and just not put it in any rulesets for now 😅 

it would really be great if rules came with corresponding min. version numbers, but that's a whole 'nother topic 😅

**Comment by p4p3r** [comment]
> I would be down to merge this and just not put it in any rulesets for now 😅

That's seems fine to me. The user that submitted feedback initially should still benefit from the updated rule as soon as they will update to 0.103.

**Comment by colleend** [comment]
ok awesome, that sounds good 👍

**Comment by colleend** [comment]
ah shoot, I just realized that this rule is already in the `dockerfile` rule-pack, and pushing this out means that people who don't have upgraded semgrep versions and who try to run the `dockerfile` pack will encounter failures. Should've checked this before merging, my bad. 

I do remember we agreed with the CLI team to not release rules with new features until after waiting ~2 weeks in order to make sure people have time to upgrade -- is this still true? @minusworld

**Comment by minusworld** [comment]
If it passes the historical tests, then we shouldn't have to worry about it. If it fails, then we should wait until it passes (I think ~3 weeks) @colleend @p4p3r

**Pull request merged**
