### PR TITLE
Python logger credential exposure audit rule

### PR DESCRIPTION
**Pull request by chgg-kboberg**
Adds an audit rule for potential disclosure of sensitive data via logger format strings

### CODE REVIEW

**Comment by ievans** [comment]
@minusworld this one has been sitting out for a while and I know Kurt already signed the CLA -- any chance we can get it merged soon?

**Comment by minusworld** [comment]
@cla-bot check

**Comment by minusworld** [comment]
Oh my

**Review by minusworld — APPROVED** [review]
👍

**Pull request merged**
