### PR TITLE
Normalize all rule YAML to the default ruamel output format

### PR DESCRIPTION
**Pull request by rcoh**
As requested, normalize YAML to:
1. Ruamel default indentation format
2. Line length of 120

If we want a slightly different format, lmk. Adds a pre-commit hook to do the formatting.

### CODE REVIEW

**Review by minusworld — APPROVED** [review]

**Comment by ievans** [comment]
@DrewDennison can these rules also be applied to the defaults on semgrep.live and the default .semgrep.yml?

**Comment by rcoh** [comment]
@ievans since these both use `ruamel` with the default settings, we _should_ be good. the default `.semgrep.yml` should be changed though

**Comment by DrewDennison** [comment]
yes what Russell said

**Comment by rcoh** [comment]
Just verified with an intentionally poorly formatted rule from semgrep.live -- pre-commit passes #543

**Comment by ievans** [comment]
I meant if you go to semgrep.live in an incognito window, the flask-secure-set-cookie rule I don't think follows these formatting conventions. Minor nit.

**Pull request merged**
