### PR TITLE
[JS] angular: security: Fix rules to use the latest Semgrep features

### PR DESCRIPTION
**Pull request by IagoAbal**
In Semgrep v0.38.0 we released flow-based constant propagation.

In Semgrep v0.58.0 we released a new iteration of taint-mode that should
(we hope) allow us to get rid of fake-taint rules.

Let's use them!

### CODE REVIEW

**Review by inkz — DISMISSED** [review]
awesome! thanks for doing it :+1:

**Comment by minusworld** [comment]
@inkz Do we still want to check the perf on these?

**Comment by IagoAbal** [comment]
> @inkz Do we still want to check the perf on these?

I can run some benchmarks, is there any specific JS repo(s) that we consider very important to measure against? Otherwise I try with whatever is in semgrep/perf.

**Comment by minusworld** [comment]
Whatever is in `perf/` is fine. If there's nothing in there, you can find a random Angular repository and use that

**Comment by IagoAbal** [comment]
I'm using our benchmark for parsing stats, need to dig a bit more into this... it's ~25k files and the new rules take almost 20 times longer... but they also give 5 times more findings...

**Comment by IagoAbal** [comment]
Partly it's due to minimized JS files that we should not be analyzing in the first place...

**Comment by IagoAbal** [comment]
I think this is because `-filter_irrelevant_rules` (aka `-fast`) doesn't work as well for taint-mode rules. Need to fix that.

**Comment by IagoAbal** [comment]
Fixed by returntocorp/semgrep#3749, we can merge this next week when 0.64.0 is released.

**Review by inkz — APPROVED** [review]
Amazing!

**Pull request merged**
