### PR TITLE
add permissive-cors rule

### PR DESCRIPTION
**Pull request by inkz**
rule for: https://github.com/returntocorp/semgrep-rules/issues/457

### CODE REVIEW

**Comment by inkz** [comment]
the rule tackles both Spring framework and general Servlet cases, so I do not know what section it suits better

**Review by minusworld — APPROVED** [review]
yesssss!!

**Comment by inkz** [comment]
updated the rule to use regex in order to find `Access-Control-Allow-Origin` case insensitively and also tackle it's value if it contains `*` or is `Null` (case insensitively also)

**Review by minusworld — APPROVED** [review]
😂 It works!

I don't know if we have any new features available with `pattern-regex` but it might be worth looking in to for future rules: https://github.com/returntocorp/semgrep/issues/688

**Pull request merged**
