### PR TITLE
Include GCM rule for hardcoded IV/nonce part 2

### PR DESCRIPTION
**Pull request by inkz**
slightly updated version of https://github.com/returntocorp/semgrep-rules/pull/1329

### CODE REVIEW

**Comment by inkz** [comment]
`todoruleid`s are blocked by https://github.com/returntocorp/semgrep/issues/2728

**Review by colleend — APPROVED** [review]
yay! GCM nonce reuse rules :D

**Comment by securingapps** [comment]
Thank you !

**Comment by colleend** [comment]
Thank **you** for contributing!

**Pull request merged**
