### PR TITLE
Adding DART support + XSS

### PR DESCRIPTION
**Pull request by AlekKras**
Hello,

Adding some detection around XSS for DART. This is more of a test run to see if I get the procedure right and testing out the small rule based on this (https://github.com/dart-lang/sdk/security/advisories/GHSA-hfq3-v9pv-p627). 

I appreciate your time, semgrep is 🔥

### CODE REVIEW

**Comment by 0xDC0DE** [comment]
Hey @AlekKras. Thanks for your contribution.

Your rule is currently invalid. You can test this by running
`semgrep --config xss.yaml xss.dart`

Some of the issues:
- Currently dart is not supported by Semgrep, but you can try to use [Semgrep's generic mode](https://semgrep.dev/docs/experiments/generic-pattern-matching/).
- Your rule file is missing `rules` as top-level key, which is necessary for semgrep's cli.
- All clauses under the `pattern-either` are functionally 'OR'. Based on your testcases, I suspect you want the pattern to be inside `Element.html(...)` 'AND' one of the options in your list of patterns. For 'AND' functionality you will have to use `patterns:` instead. 
- Unfortunately your test case on line 40 will not yet match by this rule because of the limitations for the Semgrep Generic matching. You can try to workaround this with some more complicated patterns, using metavariables.

Once you think your rule is working, you can verify your test cases with
`semgrep --test`

I recommend you try writing rules using our playground on semgrep.dev/playground
For reference, I've updated your rule here: https://semgrep.dev/s/EpnE

**Comment by 0xDC0DE** [comment]
Because we don't currently support dart, our convention would be to store rules for dart in a `/generic/dart/` folder instead of a top level `/dart` folder, like you currently do.

**Comment by AlekKras** [comment]
Hmm, got it, thank you @pieterdc1!!! 
I talked in Slack in r2c here (https://r2c-community.slack.com/archives/C01LNF69F9B/p1653433062820769) about how to add Dart, just wanted to confirm that is there a tree-sitter that I need to add?

**Comment by 0xDC0DE** [comment]
If you want to add support for dart, you have to do so in our other repositories. This repository is strictly for writing rules.

You can find more information in the docs, here: 
- https://semgrep.dev/docs/contributing/semgrep-core-contributing/#adding-support-for-a-language
- https://github.com/returntocorp/ocaml-tree-sitter-languages/blob/main/doc/adding-a-language.md

I don't have much experience yet working on semgrep-core, but I am sure there are plenty of r2c'ers ready to help you in slack and in those repositories. Good luck!

**Comment by AlekKras** [comment]
Still working on it, just hadn't had enough time.

**Comment by colleend** [comment]
hey Alex! would you happen to have time to work on this in the future? If not we can make some edits and get this merged 👍

**Comment by AlekKras** [comment]
Hey @colleend, I am trying to find some time, but might not have within the next 2 weeks unfortunately 😢 if you have suggestions for the edits, I'd be happy to make those and get this merged though!

**Comment by AlekKras** [comment]
still working on it.

**Pull request closed without merging**
