### PR TITLE
Use C typed metavariables to check incorrect C-string comparison

### PR DESCRIPTION
**Pull request by mschwager**

### CODE REVIEW

**Comment by colleend** [comment]
should we recommend strncmp instead of strcmp? 🤔 🤔

**Comment by mschwager** [comment]
> should we recommend strncmp instead of strcmp? thinking thinking

There may be situations where `strncmp` is preferable, but not necessarily for security reasons. Since `str{n}cmp` doesn't write to memory, it only reads it, we don't have the same concerns as with things like `strcpy`.

I think `strcmp` provides the most general autofix since `strncmp` is situation dependent.

See also: https://stackoverflow.com/questions/30190460/advantages-of-strncmp-over-strcmp

**Comment by colleend** [comment]
makes sense!

**Review by colleend — APPROVED** [review]
nice!!

**Pull request merged**
