### PR TITLE
Add a PR template

### PR DESCRIPTION
**Pull request by minusworld**

### CODE REVIEW

**Review by colleend — APPROVED** [review]
nice!

**Comment by mschwager** [comment]
Can we simplify this to a basic checklist? Something like:

- [ ] Associated Github issue (if applicable)
- [ ] **True positive** and **true negative** test case ([Testing rules](https://semgrep.dev/docs/writing-rules/testing-rules/))
- [ ] Metadata links to references, examples, exceptions, etc
- [ ] Actionable rule message (`<link to information about good rule messages>`)

**Comment by minusworld** [comment]
> Can we simplify this to a basic checklist? Something like:
> 
> * [ ]  Associated Github issue (if applicable)
> * [ ]  **True positive** and **true negative** test case ([Testing rules](https://semgrep.dev/docs/writing-rules/testing-rules/))
> * [ ]  Metadata links to references, examples, exceptions, etc
> * [ ]  Actionable rule message (`<link to information about good rule messages>`)

A lot of the info in this PR template is duplicated from an Issue template. I thought it might be good to repeat that information here. Which do you think is more clear about what to do next? I can see the merits of both.

**Comment by minusworld** [comment]
@cla-bot

**Comment by minusworld** [comment]
@cla-bot check

**Pull request merged**
