### PR TITLE
Add Typescript to languages of javascript/lang/ and javascript/browser/ rules

### PR DESCRIPTION
**Pull request by minusworld**
```
✗ semgrep -f javascript/lang/ ~/r2c/semgrep-app/frontend/src  
running 27 rules...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|27/27
/Users/grayson/r2c/semgrep-app/frontend/src/screens/deployment/policies/operations.ts
severity:warning rule:javascript.lang.best-practice.javascript-prompt: found prompt() call; should this be in production code?
55:  let policyName = prompt("New Policy Name:");

/Users/grayson/r2c/semgrep-app/frontend/src/screens/editor/EditorScreen.tsx
severity:warning rule:javascript.lang.best-practice.javascript-prompt: found prompt() call; should this be in production code?
558:    const loadThisUrl = prompt(
559:      `enter the URL to a ${this.state.language} file: `
560:    );
ran 27 rules on 164 files: 2 findings
6 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

### CODE REVIEW

**Comment by minusworld** [comment]
Closes https://github.com/returntocorp/semgrep-app/issues/920.

**Review by DrewDennison — APPROVED** [review]

**Comment by DrewDennison** [comment]
note that I'm 99% sure the "category" comes from the folder which means this won't show up in the registry under the a "typescript" lang cc @ievans

**Comment by ievans** [comment]
Yes that's true @DrewDennison we need a "if (js) add (ts) tag in the frontend

**Comment by minusworld** [comment]
Superceded by https://github.com/returntocorp/semgrep-rules/pull/965

**Pull request closed without merging**
