### PR TITLE
Kotlin rules

### PR DESCRIPTION
**Pull request by colleend**
* ported from findsecbugs
* converting Java rules to Kotlin

### CODE REVIEW

**Review by inkz — CHANGES_REQUESTED** [review]
where are the rules? :)

**Comment by aryx** [comment]
something went wrong here :)

**Review by aryx — CHANGES_REQUESTED** [review]
please, add some rules.

**Comment by colleend** [comment]
🤣  how did this happen?!?! 🤣  I need a git tutorial 🤦

**Review by aryx — APPROVED** [review]

**Review by inkz — APPROVED** [review]

**Pull request merged**
