### PR TITLE
Adding migrated Azure checkov rules to Azure terraform checks

### PR DESCRIPTION
**Pull request by mertcancoskuner**
Addressing https://github.com/returntocorp/semgrep-rules/issues/1693

### CODE REVIEW

**Comment by kurt-r2c** [comment]
fix for `azure-appservice-disallowed-cors`: https://semgrep.dev/s/returntocorp:azure-appservice-disallowed-cors

test cases for `azure-automation-encrypted` seem incorrect or incomplete: https://semgrep.dev/s/returntocorp:azure-automation-encrypted

**Comment by mertcancoskuner** [comment]
> fix for `azure-appservice-disallowed-cors`: https://semgrep.dev/s/returntocorp:azure-appservice-disallowed-cors
> 
> test cases for `azure-automation-encrypted` seem incorrect or incomplete: https://semgrep.dev/s/returntocorp:azure-automation-encrypted

Thanks for the fix for the cors check! Can you expand a bit upon what is the problem with the test cases for me to look further? We are aiming to look for `encrypted = true` in there as neither `encrypted = false` nor `no value` make variables encrypted.

**Comment by kurt-r2c** [comment]
@mertcancoskuner the `azure-automation-encrypted` test case that is failing is because the resource type doesn't match your condition - it is a `datetime` object not a `string` object:

```hcl
# fail
# ruleid: azure-automation-encrypted
resource "azurerm_automation_variable_datetime" "example" {
    name                    = "tfex-example-var"
    resource_group_name     = azurerm_resource_group.example.name
    automation_account_name = azurerm_automation_account.example.name
    value                   = "Hello, Terraform Basic Test."
}
```

**Comment by mertcancoskuner** [comment]
> @mertcancoskuner the `azure-automation-encrypted` test case that is failing is because the resource type doesn't match your condition - it is a `datetime` object not a `string` object:
> 
> ```terraform
> # fail
> # ruleid: azure-automation-encrypted
> resource "azurerm_automation_variable_datetime" "example" {
>     name                    = "tfex-example-var"
>     resource_group_name     = azurerm_resource_group.example.name
>     automation_account_name = azurerm_automation_account.example.name
>     value                   = "Hello, Terraform Basic Test."
> }
> ```

I fixed the patterns accordingly

**Review by inkz — CHANGES_REQUESTED** [review]
Rules from `best-practice` category located in `security` directory, I suggest moving them to `best-practice` dir

**Comment by mertcancoskuner** [comment]
> Rules from `best-practice` category located in `security` directory, I suggest moving them to `best-practice` dir

Migrated `best-practice` categories to the respective folder and included additional checks as `batch 2`

**Comment by minusworld** [comment]
bump

**Comment by colleend** [comment]
Hi Mert! 

Thanks so much for contributing to semgrep-rules, we always appreciate any rule contributions (and of so many rules, too!). Here's a list of things that I've seen that would improve the rules (I realized I could have commented on the rules themselves in the PR, but I started writing them down in a doc and just continued with it, sorry!) : 

_Rule Review:_

*best-practice*

- adding in reference links to checkov checks in the `metadata` like (medium priority):
    
```jsx
    references:
    - https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/azure/StorageAccountDisablePublicAccess.py
```
    
- replacing the `pass` in test files with `#ok: ruleid` (we don’t truly need this, but would be nice to have)

*specific to rules*

- terraform/azure/best-practice/azure-appservice-python-version.yaml — latest python version is 3.10, change that to be accurate
- terraform/azure/best-practice/azure-functionapp-http-version-latest.yaml — add ellipses inside ‘site config’ (line 10)
- terraform/azure/best-practice/azure-keyvault-enables-firewall-rules-settings.yaml — add ellipsis in between network_acls and after the } (lines 10, 12, 13)
- terraform/azure/best-practice/azure-monitor-log-profile-categories.yaml — add ellipsis with categories (line 10)
- terraform/azure/best-practice/azure-mysql-geo-backup-enabled.yaml — missing pattern-inside (PI) azurerm_mysql_server
- terraform/azure/best-practice/azure-mysql-server-tlsenforcement-enabled.yaml — missing pattern-inside
- terraform/azure/best-practice/azure-mysql-threat-detection-enabled.yaml — missing pattern-inside
- terraform/azure/best-practice/azure-postgresql-server-connection-throttling-enabled.yaml — missing pattern-inside for postgresql servers
- terraform/azure/best-practice/azure-postgresql-server-log-checkpoint-enabled.yaml — missing pattern-insides
- terraform/azure/best-practice/azure-postgresql-server-log-connections-enabled.yaml — missing pattern-inside
- terraform/azure/best-practice/azure-postgresql-ssl-enforcement-enabled.tf — missing PI (pattern-inside)
- terraform/azure/best-practice/azure-postgresql-threat-detection-enabled.yaml — missing PI, ellipsis between thread_detection_policy
- terraform/azure/best-practice/azure-secret-content-type.yaml — missing PI
- terraform/azure/best-practice/azure-secret-expiration-date.yaml — missing PI
- terraform/azure/best-practice/azure-securitcenter-email-alert.yaml — missing PI
- terraform/azure/best-practice/azure-securitycenter-contact-emails.yaml — missing PI
- terraform/azure/best-practice/azure-securitycenter-contact-phone.yaml — missing PI
- terraform/azure/best-practice/azure-securitycenter-email-alert-admins.yaml — missing PI
- terraform/azure/best-practice/azure-securitycenter-standard-pricing.yaml — missing PI
- terraform/azure/best-practice/azure-sqlserver-email-alerts-enabled.yaml — missing PI
    - missing ellipsis after the `[”...”]` — like `[”...”, ...]`
- terraform/azure/best-practice/azure-sqlserver-email-alerts-toadmins-enabled.yaml — missing PI
- terraform/azure/best-practice/azure-sqlserver-threat-detection-types.yaml — missing PI
- terraform/azure/best-practice/azure-synapse-workscape-enables-managed-virtual-network.yaml — missing PI
- terraform/azure/best-practice/azure-vmscale-sets-auto-os-image-patching-enabled.yaml — missing PI
    - missing ellipsis in os_profile_windows_config
- terraform/azure/security/aks/azure-aks-apiserver-auth-ip-ranges.yaml
    - use ellipsis instead of ellipsis in quotes
- terraform/azure/security/appservice/azure-appservice-min-tls-version.yaml — add a clause for 1.0 in pattern
- terraform/azure/security/azure-cosmosdb-accounts-restricted-access.yaml — ip_range_filter: `[…]` instead of `[”…”]`
- terraform/azure/security/azure-cosmosdb-have-cmk.yaml — for `key_vault_key_id`, use `...` instead of `"..."` in case people use non-strings
- terraform/azure/security/azure-customrole-definition-subscription-owner.yaml — have another pattern-inside with `- pattern-inside: actions = ...` and remove the actions part of the current pattern-inside. Can also add `azurerm_role_definition` as part of the pattern-inside.
- terraform/azure/security/azure-datalake-store-encryption.yaml — use pattern-not-inside resource azurerm_data_lake_store "..." { ... encryption_state = "Enabled" ...}}
    - and the pattern-inside azurerm_data_lake_store.
- terraform/azure/security/azure-functionapp-disallow-cors.yaml: change message to “ensure that CORS disallows all resources to access Function app”
- terraform/azure/security/azure-instance-extensions.yaml — add `pattern-either` with `pattern-inside: resource azure_rm_linux_virtual_machine` and `pattern-inside: resources azurerm_windows_virtual_machine`
- terraform/azure/security/azure-iot-no-public-network-access.yaml — should have `pattern-not-inside` with `public_network_access_enabled=false` instead
- terraform/azure/security/azure-managed-disk-encryption-set.yaml — use `...` instead of `"..."` in case people use non-strings in `disk_encryption_set_id`
- terraform/azure/security/azure-mariadb-public-access-disabled.yaml — missing pattern-inside
- terraform/azure/security/azure-monitor-log-profile-retention-days.yaml — use `pattern-inside` like in [https://semgrep.dev/s/vkBW](https://semgrep.dev/s/vkBW) **,** as retention_policy is required. Will have to change test case to match.
- terraform/azure/security/azure-mssql-service-mintls-version.yaml — add an “1.0” pattern too (1.0 should not be min version)
- terraform/azure/security/azure-mysql-encryption-enabled.yaml — missing pattern-inside
- terraform/azure/security/azure-mysql-mintls-version.yaml — add “TLS1_0” too
- terraform/azure/security/azure-mysql-public-access-disabled.yaml — missing pattern-inside
- terraform/azure/security/azure-network-watcher-flowlog-period.yaml — something like [https://semgrep.dev/s/dp3n](https://semgrep.dev/s/dp3n), as retention_policy is required. Second `fail` case we don’t need to catch, as we’re not sure whether its above 90 or not.
- terraform/azure/security/azure-postgresql-encryption-enabled.yaml — missing pattern-inside
- terraform/azure/security/azure-postgresql-min-tls-version.yaml — TLS1_1 and TLS 1_0
    - add pattern-inside: $RESOURCE “azurerm_postgresql_server” “…” {…}
- terraform/azure/security/azure-postgresql-server-public-access-disabled.yaml — add pattern inside
- terraform/azure/security/azure-redis-cache-public-network-access-enabled.yaml — add pattern-inside
- terraform/azure/security/azure-scale-set-password.yaml — pattern-inside with azurerm_linux_virtual_machine_scale_set
- terraform/azure/security/azure-search-publicnetwork-access-disabled.yaml — pattern-inside missing
- terraform/azure/security/azure-service-fabric-cluster-protection-level.yaml — ellipsis in `parameters` missing (parameters = {… name = x value = y …})
    - pattern-inside missing
- terraform/azure/security/azure-sqlserver-public-access-disabled.yaml — missing pattern-inside
- terraform/azure/security/azure-storage-account-minimum-tlsversion.yaml — missing pattern-inside, should also add a pattern-not-inside with TLS1_3
- terraform/azure/security/azure-storage-blob-service-container-private-access.yaml — missing pattern inside
- terraform/azure/security/azure-storage-sync-public-access-disabled.yaml — missing pattern-inside
- terraform/azure/security/azure-vmencryption-at-host-enabled.yaml — missing pattern-inside

---

Please feel free to ask me if you have any questions! Really appreciate your contributions 🙏

**Comment by mertcancoskuner** [comment]
> Hi Mert!
> 
> Thanks so much for contributing to semgrep-rules, we always appreciate any rule contributions (and of so many rules, too!). Here's a list of things that I've seen that would improve the rules (I realized I could have commented on the rules themselves in the PR, but I started writing them down in a doc and just continued with it, sorry!) :
> 
> _Rule Review:_
> 
> _best-practice_
> 
> * adding in reference links to checkov checks in the `metadata` like (medium priority):
> 
> ```js
>     references:
>     - https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/azure/StorageAccountDisablePublicAccess.py
> ```
> 
>  * replacing the `pass` in test files with `#ok: ruleid` (we don’t truly need this, but would be nice to have)
> 
> _specific to rules_
> 
> * terraform/azure/best-practice/azure-appservice-python-version.yaml — latest python version is 3.10, change that to be accurate
> * terraform/azure/best-practice/azure-functionapp-http-version-latest.yaml — add ellipses inside ‘site config’ (line 10)
> * terraform/azure/best-practice/azure-keyvault-enables-firewall-rules-settings.yaml — add ellipsis in between network_acls and after the } (lines 10, 12, 13)
> * terraform/azure/best-practice/azure-monitor-log-profile-categories.yaml — add ellipsis with categories (line 10)
> * terraform/azure/best-practice/azure-mysql-geo-backup-enabled.yaml — missing pattern-inside (PI) azurerm_mysql_server
> * terraform/azure/best-practice/azure-mysql-server-tlsenforcement-enabled.yaml — missing pattern-inside
> * terraform/azure/best-practice/azure-mysql-threat-detection-enabled.yaml — missing pattern-inside
> * terraform/azure/best-practice/azure-postgresql-server-connection-throttling-enabled.yaml — missing pattern-inside for postgresql servers
> * terraform/azure/best-practice/azure-postgresql-server-log-checkpoint-enabled.yaml — missing pattern-insides
> * terraform/azure/best-practice/azure-postgresql-server-log-connections-enabled.yaml — missing pattern-inside
> * terraform/azure/best-practice/azure-postgresql-ssl-enforcement-enabled.tf — missing PI (pattern-inside)
> * terraform/azure/best-practice/azure-postgresql-threat-detection-enabled.yaml — missing PI, ellipsis between thread_detection_policy
> * terraform/azure/best-practice/azure-secret-content-type.yaml — missing PI
> * terraform/azure/best-practice/azure-secret-expiration-date.yaml — missing PI
> * terraform/azure/best-practice/azure-securitcenter-email-alert.yaml — missing PI
> * terraform/azure/best-practice/azure-securitycenter-contact-emails.yaml — missing PI
> * terraform/azure/best-practice/azure-securitycenter-contact-phone.yaml — missing PI
> * terraform/azure/best-practice/azure-securitycenter-email-alert-admins.yaml — missing PI
> * terraform/azure/best-practice/azure-securitycenter-standard-pricing.yaml — missing PI
> * terraform/azure/best-practice/azure-sqlserver-email-alerts-enabled.yaml — missing PI
>   
>   * missing ellipsis after the `[”...”]` — like `[”...”, ...]`
> * terraform/azure/best-practice/azure-sqlserver-email-alerts-toadmins-enabled.yaml — missing PI
> * terraform/azure/best-practice/azure-sqlserver-threat-detection-types.yaml — missing PI
> * terraform/azure/best-practice/azure-synapse-workscape-enables-managed-virtual-network.yaml — missing PI
> * terraform/azure/best-practice/azure-vmscale-sets-auto-os-image-patching-enabled.yaml — missing PI
>   
>   * missing ellipsis in os_profile_windows_config
> * terraform/azure/security/aks/azure-aks-apiserver-auth-ip-ranges.yaml
>   
>   * use ellipsis instead of ellipsis in quotes
> * terraform/azure/security/appservice/azure-appservice-min-tls-version.yaml — add a clause for 1.0 in pattern
> * terraform/azure/security/azure-cosmosdb-accounts-restricted-access.yaml — ip_range_filter: `[…]` instead of `[”…”]`
> * terraform/azure/security/azure-cosmosdb-have-cmk.yaml — for `key_vault_key_id`, use `...` instead of `"..."` in case people use non-strings
> * terraform/azure/security/azure-customrole-definition-subscription-owner.yaml — have another pattern-inside with `- pattern-inside: actions = ...` and remove the actions part of the current pattern-inside. Can also add `azurerm_role_definition` as part of the pattern-inside.
> * terraform/azure/security/azure-datalake-store-encryption.yaml — use pattern-not-inside resource azurerm_data_lake_store "..." { ... encryption_state = "Enabled" ...}}
>   
>   * and the pattern-inside azurerm_data_lake_store.
> * terraform/azure/security/azure-functionapp-disallow-cors.yaml: change message to “ensure that CORS disallows all resources to access Function app”
> * terraform/azure/security/azure-instance-extensions.yaml — add `pattern-either` with `pattern-inside: resource azure_rm_linux_virtual_machine` and `pattern-inside: resources azurerm_windows_virtual_machine`
> * terraform/azure/security/azure-iot-no-public-network-access.yaml — should have `pattern-not-inside` with `public_network_access_enabled=false` instead
> * terraform/azure/security/azure-managed-disk-encryption-set.yaml — use `...` instead of `"..."` in case people use non-strings in `disk_encryption_set_id`
> * terraform/azure/security/azure-mariadb-public-access-disabled.yaml — missing pattern-inside
> * terraform/azure/security/azure-monitor-log-profile-retention-days.yaml — use `pattern-inside` like in https://semgrep.dev/s/vkBW **,** as retention_policy is required. Will have to change test case to match.
> * terraform/azure/security/azure-mssql-service-mintls-version.yaml — add an “1.0” pattern too (1.0 should not be min version)
> * terraform/azure/security/azure-mysql-encryption-enabled.yaml — missing pattern-inside
> * terraform/azure/security/azure-mysql-mintls-version.yaml — add “TLS1_0” too
> * terraform/azure/security/azure-mysql-public-access-disabled.yaml — missing pattern-inside
> * terraform/azure/security/azure-network-watcher-flowlog-period.yaml — something like https://semgrep.dev/s/dp3n, as retention_policy is required. Second `fail` case we don’t need to catch, as we’re not sure whether its above 90 or not.
> * terraform/azure/security/azure-postgresql-encryption-enabled.yaml — missing pattern-inside
> * terraform/azure/security/azure-postgresql-min-tls-version.yaml — TLS1_1 and TLS 1_0
>   
>   * add pattern-inside: $RESOURCE “azurerm_postgresql_server” “…” {…}
> * terraform/azure/security/azure-postgresql-server-public-access-disabled.yaml — add pattern inside
> * terraform/azure/security/azure-redis-cache-public-network-access-enabled.yaml — add pattern-inside
> * terraform/azure/security/azure-scale-set-password.yaml — pattern-inside with azurerm_linux_virtual_machine_scale_set
> * terraform/azure/security/azure-search-publicnetwork-access-disabled.yaml — pattern-inside missing
> * terraform/azure/security/azure-service-fabric-cluster-protection-level.yaml — ellipsis in `parameters` missing (parameters = {… name = x value = y …})
>   
>   * pattern-inside missing
> * terraform/azure/security/azure-sqlserver-public-access-disabled.yaml — missing pattern-inside
> * terraform/azure/security/azure-storage-account-minimum-tlsversion.yaml — missing pattern-inside, should also add a pattern-not-inside with TLS1_3
> * terraform/azure/security/azure-storage-blob-service-container-private-access.yaml — missing pattern inside
> * terraform/azure/security/azure-storage-sync-public-access-disabled.yaml — missing pattern-inside
> * terraform/azure/security/azure-vmencryption-at-host-enabled.yaml — missing pattern-inside
> 
> Please feel free to ask me if you have any questions! Really appreciate your contributions 🙏

Thanks @colleend! I will work on them and reach out to you for questions. One thing to note though; we didn't add reference links to AWS checks while migrating them before.

**Comment by colleend** [comment]
Got it, thanks for your quick response! Good to know about the AWS checks -- it'd be nice to have the reference links, but not a necessity 👍

**Comment by mertcancoskuner** [comment]
Hi @colleend, except the following which I need your help; 
- In `azure-postgresql-min-tls-version`, I am not sure how to implement TLS1_1 and TLS 1_0 portion.
- In `azure-aks-apiserver-auth-ip-ranges`, I couldn't manage to have `api_server_authorized_ip_ranges = ...` detect `api_server_authorized_ip_ranges = []`.

Other fixes that are specific to rules should be there now.

**Comment by colleend** [comment]
Cool, I looked over and made some slight edits -- for `azure-aks-apiserver-auth-ip-ranges`, this seems like a bug in the semgrep engine, so I'll file an issue there. I also changed the test case for `terraform/azure/security/azure-datalake-store-encryption.yaml` as the rule states for cases where `encryption_state` is not explicitly enabled, it should fail. The only other thing I changed was adding cases where multiple TLS versions should be looked at. Looks good to me now!

Again, thanks for contributing! We always love to see new contributions being made 😄

**Comment by kurt-r2c** [comment]
@inkz please re-review

**Review by colleend — APPROVED** [review]
lgtm now :D

**Review by inkz — APPROVED** [review]

**Comment by mertcancoskuner** [comment]
Thanks, @colleend, @kurt-r2c and @inkz! Looks like `semgrep-rules-test-historical / rules-test-historical (pull_request)` is still failing due to unit tests for rules that aren't changed by this commit (`avoid-tainted-http-request`, `check-send-file` and `unsafe-argon2-config`).

**Pull request merged**
