### PR TITLE
Merge copy of develop into release

### PR DESCRIPTION
**Pull request by minusworld**
Trying to do it this way because the reverts never got sync'd back into develop, so there are conflicts that would remove certain rules from develop if I tried to merge release back into develop

### CODE REVIEW

**Review by underyx — CHANGES_REQUESTED** [review]
please hold, details on slack

**Comment by kurt-r2c** [comment]
Failing tests for `tainted-html-response` and `react-props-injection`

**Review by underyx — APPROVED** [review]
release is unblocked

**Comment by underyx** [comment]
Are you sure you want to completely remove the agent test though? https://github.com/returntocorp/semgrep-rules/pull/1962/commits/feeec5bf18301f21810451f8c3a3737572c3ce1e

**Pull request merged**
